databases:
  - name: kasms_db
    database_name: kasms_db
    user: kasms_user

services:
  - type: web
    name: http://localhost:8000
    runtime: python
    buildCommand : "./build.sh"
    startCommand: "gunicorn kasms.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase: 
          name: kasms_db
          property: connectionString
          